### ISSUE TITLE
使用的Ainoaibo不打算开源了吗？

### ISSUE THREAD

**Issue by jk234ert** [ainopara/Stage1st-Reader#38]
您好，

一直在用您开发的s1客户端上论坛，应该是我手机上仅5年使用时间最长的app了。

有心想修改点UI自己用，发现项目引用的Ainoaibo打不开了，也搜索不到，希望确认下，是否没有开源的打算了？

**Comment by ainopara** [comment]
Ainoaibo 之前不记得什么原因暂时改为 private repo 了。现在已经重新设为 public 访问权限。
感谢一直以来的支持。
